CREATE DATABASE IF NOT EXISTS moinesam CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE moinesam;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS request (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    address VARCHAR(255) NOT NULL,
    contacts VARCHAR(255) NOT NULL,
    date_time DATETIME NOT NULL,
    service VARCHAR(100) NOT NULL,
    payment VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL,
    cancel_reason TEXT
);
